# kubernetes/Chart.yaml
apiVersion: v2
name: airbnb-umbrella
description: A Helm chart for deploying the entire Django+React application
type: application
version: 2.0.0
appVersion: "1.0.0"

dependencies:
  - name: backend # charts/ 디렉토리의 차트 이름과 일치해야 함
    version: "1.0.8" # backend 차트의 Chart.yaml에 있는 버전
    repository: "file://./charts/backend" # 로컬 디렉토리를 리포지토리로 지정
  - name: frontend # charts/ 디렉토리의 차트 이름과 일치해야 함
    version: "2.0.1" # backend 차트의 Chart.yaml에 있는 버전
    repository: "file://./charts/frontend" # 로컬 디렉토리를 리포지토리로 지정
  - name: postgresql # charts/ 디렉토리의 차트 이름과 일치해야 함
    version: "2.31.3" # backend 차트의 Chart.yaml에 있는 버전
    repository: "file://./charts/postgresql" # 로컬 디렉토리를 리포지토리로 지정