# Generated by Django 5.2.3 on 2025-06-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experience", "0001_initial"),
        ("media", "0001_initial"),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="room.room",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="experience",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="experience.experience",
            ),
        ),
    ]
